### ISSUE TITLE
bounds property on <GoogleMap> does not work 

### ISSUE THREAD

**Issue by TomCaserta** [tomchentw/react-google-maps#183]
I cannot seem to set the bounds on a GoogleMap component. As far as I can tell you are supposed to set the "bounds" property to be a LngLatBounds object. 

As a work around to this I attempted to call the fitBounds function directly once the component had been mounted however the map state did not exist (yet). Is there a event for when the map has initialised?

**Comment by solace** [comment]
@TomCaserta I tried using the `tilesloaded` event on the map and it seems to do the trick, although there's a delay for the update until well, the tiles are loaded. Would be best to be able to set bounds on init, but until that's supported this will do for now.

```
<GoogleMap
   ref="map"
   ...
   onTilesloaded={this.tilesLoadedHandler} >
</GoogleMap
```

**Comment by mmahalwy** [comment]
@solace option one is what i am using and works well until the parent is rerendered... any solution to that?

**Comment by solace** [comment]
@mmahalwy : Does this help: https://gist.github.com/solace/edfade8f48ce03de5ef9a1221e1c26b2 ?

**Comment by tomchentw** [comment]
We're going to look into this shortly. Close for now

We're also looking for maintainers. Involve in #266 to help strengthen our community!

**Comment by davidpelayo** [comment]
@solace anyone knows a better solution? I'm looking at how to solve the same issue, and there is no docs for doing proper fitBounds with your current markers in a markerClusterer.

**Comment by solace** [comment]
It wasn't meant to be a complete solution, just point people in the right direction.

You may have to take a look inside the lib in `node_modules` to figure out what will work for you.  Those same files will also have the functions so you can see what params they need you to pass in.  If it helps, grep for the functions used to find file they're in.

Based on how you're implementing it, you will also need to dump your objects to see what values are available to you.  It took me some trial and error to find the right combination, which is why the gist says 'YMMV'.

Good luck.

**Comment by davidpelayo** [comment]
@solace, your rebuildMarkers function looks like this now (and works):

```javascript
rebuildMarkers(markers) {
    const newBounds = new google.maps.LatLngBounds();

    if (markers.length) {
      const latLongMarkersArray = map(markers, m => pick(m, ['longitude', 'latitude']));
      each(latLongMarkersArray, (marker) => newBounds.extend(new google.maps.LatLng(marker.latitude, marker.longitude)));
    }

    let newState = {
      center: this.state.center,
      zoom: this.state.zoom
    };

    if (newBounds && this.refs.map && this.refs.map.fitBounds) {
      this.refs.map.fitBounds(newBounds);
      const newCenter = newBounds.getCenter();

      newState = {
        center: {
          lat: newCenter.lat(),
          lng: newCenter.lng()
        },
        zoom: this.state.zoom
      };
    }

    this.setState({
      center: newState.center,
      zoom: newState.zoom,
      bounds: newBounds
    });
}
```

**Comment by solace** [comment]
I'm glad you found a solution for your problem.

I can't recall at this point, and am not going to go check, but the `onChange` may have been to handle zoom in/out and dragging of the map to update the positions, otherwise when new markers come in from props, the center and bounds would jump away from where the user had them.

Of course, I could be wrong.

**Comment by davidpelayo** [comment]
@solace Now is named `onCenterChanged`.

**Comment by ryanhca** [comment]
so.... @tomchentw did fitBounds() get removed from the 'ref'. When I log this.refs.map (after putting a ref on the GoogleMap component I don't see 'fitBounds' anywhere. I can't see the ref in CDM() function, but I see it when I log it in the render portion of the component.

**Comment by LeaveNhA** [comment]
Hello fellas,

how this get closed without any further reading or proper solution?

**Comment by Vaporjawn** [comment]
A year later, still looking for a proper solution as well
