### ISSUE TITLE
Map fails to load after page navigation

### ISSUE THREAD

**Issue by luisrudge** [tomchentw/react-google-maps#202]
I have a master/detail scenario. If I open a detail page, go back to master, and open another detail page, the map fails to load:

![image](https://cloud.githubusercontent.com/assets/941075/12834612/e569c8aa-cb8f-11e5-97e0-affc4fc24ca4.png)

**Comment by luisrudge** [comment]
bump :|

**Comment by tomchentw** [comment]
Sorry I can't help with the information provided.

**Comment by luisrudge** [comment]
Ok, I'll try to come up with a repro somewhere

**Comment by dyyylan** [comment]
I'm running into the same problem, I get the same "cannot read property 'offsetWidth of null" and then mounting errors from react-google-maps.

I can't narrow down what is causing the problem, though. I created a test repo to try to break it, and have been unsuccessful so far -- it works fine there.

**Comment by dyyylan** [comment]
The source of my problem was this:

The GoogleMapsLoader was rendered when my container component was mounted, but then data was changed and it removed the GoogleMapsLoader (the container returned `null`). Then when the new data finished loading, GoogleMapsLoader was rendered again, but the offsetWidth error pops up, because when doing `new google.maps.Map` it is being fed an invalid or nonexistent DOM element.

I didn't notice this because the re-renders were so fast in my component, I didn't see that it was being loaded when the component first mounted. I'm not sure how best to solve this on your end... is the actuall google map loaded asynchronously? It seems like between rerenders the reference becomes invalid.

**Comment by dyyylan** [comment]
I was able to reproduce the problem here:
https://github.com/dyyylan/map-breaks-on-rerender

I think the cause of the problem is that the map might be added between re-renders on the component, so if it is quickly added then removed, it cannot be added again on subsequent renders.

Is this related to your problem @luisrudge ?

**Comment by luisrudge** [comment]
yep. that's exactly it. I fixed it by delaying when the map actually appears

```js
  componentDidMount() {
    setTimeout(() => this.setState({show: true}), 300);
  }
```

**Comment by tomchentw** [comment]
We're going to look into this shortly. Thanks for providing the repo:
https://github.com/dyyylan/map-breaks-on-rerender

We're also looking for maintainers. Involve in #266 to help strengthen our community!
