### ISSUE TITLE
a better way of grouping elements inside the GooglMapLoader

### ISSUE THREAD

**Issue by wnoveno** [tomchentw/react-google-maps#319]
There should be a component to easily group elements as such

```
<GoogleMap>
	<Group>    
		<Polyline />
	    <Marker />
		<Marker />
	</Group>
	<Group>
		<Polyline />
		<Marker />
		<Marker />
	</Group>
<GoogleMap>
```

Note that this would also help with react's return single element rule as well.

**Comment by jgoux** [comment]
What is the current way of doing it ?
I'm trying to connect 3 different "groups" to redux but I'm not sure which node to use at the root.

**Comment by tomchentw** [comment]
Try the new version [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318), I believe this can be done now since we use context to store google map instances instead of props.

[6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/
