### ISSUE TITLE
Error for missing API Key

### ISSUE THREAD

**Issue by MarcusHurney** [tomchentw/react-google-maps#349]
I'm getting an error in the browser console saying "Google Maps API Error: MissingKeyMapError"

I'm not sure where I am suppose to enter such an API key because I'm simply feeding the component longitude and latitude.

Here is how I am using the component: https://gist.github.com/MarcusHurney/d043af928c4c25b57a6243d769743708

**Comment by tomchentw** [comment]
@MarcusHurney I'm experiencing the same issue as well, and I believe it's a policy change in Google. Please see: https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by Echelpoel** [comment]
The error started showing up here as well - using the GeoChart. Question is where to put the API key though?

**Comment by davekiss** [comment]
As specified in the docs, place the key in the request URL when loading the maps library.

`https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY`

**Comment by cymen** [comment]
Is this actually mentioned in the docs? Because I couldn't find it. But then I found this issue so...

**Comment by tomchentw** [comment]
You should read this first:
https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by cymen** [comment]
Oh, I got the key already -- it just wasn't clear how to use the key with react-google-maps. Now, after reading the docs some more and the Google API docs, I realized this is mostly a react wrapper for the API which totally makes sense. Duplicating all the documentation would not be useful.

However, it might be good to have a simple getting started as the examples in the docs don't mention this key property in the URL. I was actually searching for key in the docs as the first step but couldn't find any mention.

**Comment by tomchentw** [comment]
I agree. Feel free to jump in into the docs section by opening a PR. Docs are located under `src/docs/installation.md`

There's a console warning for no API key is set when you load up the page without API KEY. At first, I thought that should be enough for the user to check the docs. Since configuring the project is a little complex, I'm really unwilling to add more steps to confuse the users.

Yeah, in the introduction.md page:

https://github.com/tomchentw/react-google-maps/blob/e96049d78c96e864c9ad5d24ffd66348aeec79dc/src/docs/introduction.md

The first line:

> react-google-maps provides a set of React components wrapping the underlying Google Maps JavaScript API v3 instances. Thw wrapping simply do

Which exists at the top most of the documentation site:
https://tomchentw.github.io/react-google-maps/#introduction

So clearly, the fact that ` a react wrapper for the API ` is documented there but people still miss them and keep asking me questions like how/why/what is this happening. To be honest, this is really frustrating. Do you have any ideas/suggestions on how can we improve things to make it better?

**Comment by mobitinker** [comment]
I think it's not clear to me (and others?) where to put this line, with my api key.

      <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=MY_API_KEY&callback=initMap">
      </script>

**Comment by jimjy98** [comment]
@mobitinker you should put this line in the index.html file found in the folder "public" in your react project
