### ISSUE TITLE
Map doesn't load after v4 -> v5 upgrade

### ISSUE THREAD

**Issue by benwiley4000** [tomchentw/react-google-maps#353]
I was already using the `googleMapElement` prop on `GoogleMapLoader` when I was using v4, so I'm not sure what's going wrong. I'm not doing anything with `mapHolderRef`. The tiles simply don't load. ETA: no error logs.

Here's my component:

```
const containerElement = (props) => (
  <div className='google_map'></div>
);

const mapElement = (props) => (
  <GoogleMap
    defaultZoom={5}
    defaultCenter={MAP_DEFAULT_CENTER} />
);

const DeviceMap = (props) => (
  <section className='device_map col-xs-12'>
    <GoogleMapLoader
    containerElement={containerElement(props)}
    googleMapElement={mapElement(props)} />
  </section>
);
```

**Comment by tomchentw** [comment]
Please see this comment:

> https://github.com/tomchentw/react-google-maps/issues/323#issuecomment-251857246
> I don't have a good solution either. The only thing I knew is Google Maps API requires the div to have certain dimension instead of leaving it auto.

Also,  [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/

**Comment by tomchentw** [comment]
@benwiley4000 please try 6.0.0 instead, thanks!

**Comment by benwiley4000** [comment]
@tomchentw I plan to upgrade 6 but I'm trying to take incremental steps. Your comment doesn't seem to address my issue - the parent div classes enforce the size of the map and it had no problem in version 4. I'm getting a properly sized tan pre-load map.

**Comment by tomchentw** [comment]
v6 is rewritten from scratch and has some breaking changes. Please see the `CHANGELOG.md` for more details. v5 is just an obsolete version. Don't use it.

For your code, I'm not sure why it doesn't load. Could you show me the class name definitions of `device_map` and `google_map`? Also, which version of React are you using? Since we have a bug in v4 and v5 with `react@^15` (see #327), and  I have no plan for maintaining v4 and v5, the best solution is to upgrade to v6 directly.

Please feel free to reopen the issue.

**Comment by benwiley4000** [comment]
Not sure what went wrong with version 5, but I'm now on v6 and everything works.

**Comment by tomchentw** [comment]
@benwiley4000 Great!
