### ISSUE TITLE
Custom marker changes size (and shows only part of it) on zooming

### ISSUE THREAD

**Issue by FBosler** [tomchentw/react-google-maps#539]
See SO-Post:

https://stackoverflow.com/questions/45119457/react-google-maps-marker-resizes-after-zooming

**Comment by FBosler** [comment]
This now also happens when instantiating the marker like this on first instantiation....
					```
	icon: {
								url: icon_url(this.props.markerIcon,'purple'),
								size: new google.maps.Size(40, 60),
								anchor: new google.maps.Point(20,60),
							  }
```

**Comment by rizkiandrianto** [comment]
me too had this problem

**Comment by vincentvella** [comment]
Just add a width and a height in the SVG code and then set the size of it within the icon like you are doing.

**Comment by FBosler** [comment]
How would I do add a height in the SVG code?

**Comment by vincentvella** [comment]
Inside the <svg> tag create a width="28" and a height="40"...Try that out and let me know if that works.

**Comment by FBosler** [comment]
This took a little while, sorry for not getting back to you earlier. I knew from past experiences that maps are crazy annoying so I worked on other stuff. But now I am back here, problem still not fixed, I tried setting a fixed width and hight and get the same results.

**Comment by FBosler** [comment]
@rizkiandrianto how did you solve it?

**Comment by tomchentw** [comment]
I understand this is frustrated, but this is not a support form on how to use Google Maps API. `react-google-maps` is simply a wrapper around it. Unless there's a specific issue on the `react-google-maps` itself, please post your questions on StackOverflow instead of creating an issue here.

The maintainers only have limited time on open source projects. Please help us keep the health ecosystem. Thanks!
