### ISSUE TITLE
InfoWindow in DirectionsRenderer component

### ISSUE THREAD

**Issue by yasmineA** [tomchentw/react-google-maps#556]
Hi, please how can i change the content of infoWindows for DirectionsRenderer ? 
I followed this exemple https://tomchentw.github.io/react-google-maps/basics/directions it works like a charm but i want to change the content of the pop-up infoWindow
Thank you in advance

**Comment by oshalygin** [comment]
This isn't very straightforward, because every location can potentially have different infoWindow content.  There are a number of solutions on the web, but if anyone else has any "cleaner" solution, please post it.

Further reading:
https://groups.google.com/forum/#!msg/google-maps-js-api-v3/F72bOyl1Sqc/oU1jHS6d4BUJ
https://developers.google.com/maps/documentation/javascript/3.exp/reference#InfoWindowOptions
https://stackoverflow.com/questions/29361044/setting-a-info-window-for-google-map-markers-located-on-route-start-and-end-poi

With `<DirectionsRenderrer />` you have access to the `options` prop, which allows you to do alot of this, but again this super straightforward.

**Comment by tomchentw** [comment]
I understand this is frustrated, but this is not a support form on how to use Google Maps API. `react-google-maps` is simply a wrapper around it. Unless there's a specific issue on the `react-google-maps` itself, please post your questions on StackOverflow instead of creating an issue here.

The maintainers only have limited time on open source projects. Please help us keep the health ecosystem. Thanks!
