### ISSUE TITLE
Auto Suggest Not Working.

### ISSUE THREAD

**Issue by PinkPanda17** [tomchentw/react-google-maps#577]
Hi, I got this code on my searchbox the searchbox and map is showing fine the only problem is there are no auto suggest popping up whenever i type

<SearchBox
      ref={props.onSearchBoxMounted}
      bounds={props.bounds}
      controlPosition={google.maps.ControlPosition.TOP_CENTER}
      onPlacesChanged={props.onPlacesChanged}
      inputPlaceholder="Enter Your Default Location Here"
/>

handleSearchBoxMounted(searchBox){
        this._searchBox=searchBox;
    }

    handlePlacesChanged()
    {
        const places=this._searchBox.getPlaces();
        console.log(places)
    }

but there isn't any auto suggest , though i can get places. Any thoughts about this?

**Comment by PinkPanda17** [comment]
so I found the problem , it actually shows but the selection appears behind the map. Any way to fix this?

**Comment by oshalygin** [comment]
This is likely an issue with z-index.  I'm going to close this because this happens very frequently when working with google maps.

If you look at the demo it should be just fine:
https://tomchentw.github.io/react-google-maps/places/search-box

Again, please try modifying the zindex on various components.
