### ISSUE TITLE
Using custom `InfoWindow` with `DirectionsRenderer`

### ISSUE THREAD

**Issue by JennerF** [tomchentw/react-google-maps#644]
I have a potential bug that I'm trying to work through. I've posted a SO question [here](https://stackoverflow.com/q/46419408/4044442) but it has yet to receive any answers.

Any help here would be greatly appreciated. Thank you!

**Comment by tomchentw** [comment]
>  I imagine that the package is mostly a wrapper around the Google Maps javascript API. 

Yes. Nothing more.

The problem with your code is you're using
> defaultOptions={{

with `this.state`.

The `defaultOptions` will be called once upon its first mount, and it will not reflect any state changes at all (corresponds to `defaultValue` for the `<input>` element).

You should change it to `options` instead.

**Comment by tomchentw** [comment]
I understand this is frustrated, but this is not a support form on how to use Google Maps API. `react-google-maps` is simply a wrapper around it. Unless there's a specific issue on the `react-google-maps` itself, please post your questions on StackOverflow instead of creating an issue here.

The maintainers only have limited time on open source projects. Please help us keep the health ecosystem. Thanks!
