### ISSUE TITLE
Rendering Multiple Markers

### ISSUE THREAD

**Issue by Siyanda-Mzam** [tomchentw/react-google-maps#650]
May you please give an example on how to render multiple markers with infoWindows? I have tried but it does not want to render any marker with infowindow wrapped around a div. It only works if I render a collection of a single component, that is, a collection of just markers. But if I extend this and add infoWindows too, it won't render anything.

This is my Map Component:

```
     <Map google={this.props.google}
            zoom={16}
            initialCenter={{
            lat: -26.107567,
            lng: 28.056702
          }}
      enableEventPropagation={true}
      mapTypeControl={false}
      streetViewControl={false}

      disableDefaultUI={true}
      centerAroundCurrentLocation={false}
      onClick={this.onMapClick}
      >
      {this.state.markerCollection}
      <Search setMarkersData={this.setMarkers} updateMarkersData={this.updateMarkers}/>
      </Map>
```

The state has a marker collection which is simply an array of divs with `Marker` and `infoWindow` components inside. I also get this warning: ```Warning: Unknown props `map`, `google`, `mapCenter` on <div> tag. Remove these```

**Comment by tomchentw** [comment]
Don't have enough information for me to debug the code, please provide a minimal reproducible repository so that others can help.

**Comment by tomchentw** [comment]
I understand this is frustrated, but this is not a support form on how to use Google Maps API. `react-google-maps` is simply a wrapper around it. Unless there's a specific issue on the `react-google-maps` itself, please post your questions on StackOverflow instead of creating an issue here.

The maintainers only have limited time on open source projects. Please help us keep the health ecosystem. Thanks!

**Comment by arunaveeram** [comment]
Hi can you please tell how to use initial center and two markers at a time on the map
