### ISSUE TITLE
Change Info-window size without lag

### ISSUE THREAD

**Issue by Sepehr-Aliakbary70** [tomchentw/react-google-maps#653]
I want to use info-window on google map. the content of my info window has an images. when I use "maxWidth" in info-window, It insert some margin and padding as following screenshot. I tried this css code: 

` .gm-style .gm-style-iw{     
font-weight: 300;     
font-size: 13px;     
overflow: hidden;     
width: 210px  !important;     
top: auto !important;     
position: absolute;     
left: auto !important;     
bottom: auto !important;  
 }`

but after using the above code, my info-window gets some lags. Please tell me How can I use info-window without any padding or [margin.](url
![untitled](https://user-images.githubusercontent.com/6781518/31307273-778e2d3e-ab6d-11e7-967f-03bbc1bea165.png)
)

**Comment by ztanner** [comment]
You will probably have more control over styling without needing hacks if you use InfoBox. https://tomchentw.github.io/react-google-maps/#infobox

**Comment by tomchentw** [comment]
I understand this is frustrated, but this is not a support form on how to use Google Maps API. `react-google-maps` is simply a wrapper around it. Unless there's a specific issue on the `react-google-maps` itself, please post your questions on StackOverflow instead of creating an issue here.

The maintainers only have limited time on open source projects. Please help us keep the health ecosystem. Thanks!
