### ISSUE TITLE
Unable to clear polygon from map.

### ISSUE THREAD

**Issue by hrushilok** [tomchentw/react-google-maps#661]
Hello, I have used Polygon component. Now I am unable to clear polygon from map after I crate it using drawing manager.

**Comment by tomchentw** [comment]
I understand this is frustrated, but this is not a support form on how to use Google Maps API. `react-google-maps` is simply a wrapper around it. Unless there's a specific issue on the `react-google-maps` itself, please post your questions on StackOverflow instead of creating an issue here.

The maintainers only have limited time on open source projects. Please help us keep the health ecosystem. Thanks!
