### ISSUE TITLE
Mixing Polygons, Clusters, Markers and InfoWindow

### ISSUE THREAD

**Issue by erickvica** [tomchentw/react-google-maps#662]
I got the way to combine them but now is just a matter of being repeating the information when I click Marker and get InfoWindow, I made an unsolved question here:
[https://stackoverflow.com/questions/46695680/adding-multiple-markers-with-infowindows-google-maps-api-reactjs]

**Comment by tomchentw** [comment]
I understand this is frustrated, but this is not a support form on how to use Google Maps API. `react-google-maps` is simply a wrapper around it. Unless there's a specific issue on the `react-google-maps` itself, please post your questions on StackOverflow instead of creating an issue here.

The maintainers only have limited time on open source projects. Please help us keep the health ecosystem. Thanks!

**Comment by erickvica** [comment]
Thanks Tom, I'm gonna take it into consideration!
