### ISSUE TITLE
Get wrapped coordinates using getCenter()

### ISSUE THREAD

**Issue by zackperdue** [tomchentw/react-google-maps#667]
Having trouble getting the coordinates at center when using `getCenter()` method. The Longitude comes out larger than 180, which breaks some things.

What is the recommended way to get this? I've dug through the API and I can't find anything out of the box.

Thanks.

**Comment by tomchentw** [comment]
I cannot see there's a relationship with your issue with `react-google-maps`. Please submit a minimal repository to reproduce your issue if you really want some help.
---
I understand this is frustrated, but this is not a support form on how to use Google Maps API. `react-google-maps` is simply a wrapper around it. Unless there's a specific issue on the `react-google-maps` itself, please post your questions on StackOverflow instead of creating an issue here.

The maintainers only have limited time on open source projects. Please help us keep the health ecosystem. Thanks!
