### ISSUE TITLE
Show users current location on map

### ISSUE THREAD

**Issue by siddushar** [tomchentw/react-google-maps#736]
Is there way to indicate user current location using blue dot icon.

**Comment by alexrussell** [comment]
Nothing built in that I know of, but I imagine you can very easily add it as a marker with a custom icon. But you would have to implement the stuff that tracks the user's location in order to update the location of the marker (see [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/watchPosition) for some docs on that).

**Comment by tomchentw** [comment]
GitHub issue tracker is NOT designed for **how to** questions
