### ISSUE TITLE
Mount InfoBox content and OverlayView content directly to their respective DOM

### ISSUE THREAD

**Issue by thetiby** [tomchentw/react-google-maps#93]
Right now, an empty, otherwise useless, div is used to account for the fact that React needs to render to a DOM element. There's actually access to the underlying InfoBox/OverlayView div under `instance.div_` which will eliminate the need for that React "crutch".

**Comment by tomchentw** [comment]
Thanks for the great discussion and open an issue for me! Will try to add a PR soon :)

**Comment by tomchentw** [comment]
Feel free to submit a PR. Close for now

We're also looking for maintainers. Involve in #266 to help strengthen our community!

**Comment by jamesmosier** [comment]
I know this issue is super old, but could you provide some more insight into what the proposed solution is for removing the unneeded `div` so that something like `z-index` could be applied to an OverlayView @thetiby ?

I understand that you probably haven't thought about this since the day the issue opened, but I'd love to contribute to fix this but want to make sure I head down the right path.

**Comment by thetiby** [comment]
@jamez14 you might be able to apply the z-index to the child div that you have control over; if not, check the `InfoBoxInstance.div_`, if it still exits

**Comment by jamesmosier** [comment]
I should've just tried to apply it to the child `div` from the start 🤦‍♂️  that did it. Thanks @thetiby !
