### ISSUE TITLE
New Google maps api version 3.34 causes error

### ISSUE THREAD

**Issue by DaddyWarbucks** [tomchentw/react-google-maps#934]
I am not 100% sure this is specifically a `react-google-maps` bug. But, the release of the "latest" Google Maps API version 3.34 caused my working code to break. Please see this repo for a demonstration of the "error".

The map renders on first "mount", but subsequent mounts do not render the map.

https://github.com/pxlpotion/react-google-maps-error-demo

```
yarn
yarn start
```

All relevant code is in `src/App.js` and `public/index.html`. Simply start the app and view the index, which has some explanation and a demo of the "error"

**Comment by sakhisheikh** [comment]
Please add a little description of error here. Is it about remove NodeType error?
Thanks.

**Comment by DaddyWarbucks** [comment]
There really is no error thrown. The map does mount again, but it only displays a gray background. Please see attached screenshot.
<img width="1440" alt="screen shot 2018-11-12 at 2 10 29 pm" src="https://user-images.githubusercontent.com/4671808/48372685-f973fd80-e684-11e8-8029-a2afbf2e8d7e.png">

**Comment by OrenSchwartz** [comment]
experiencing same issue

**Comment by usamamashkoor** [comment]
Any one found solution for this yet..?

**Comment by davidlarcher** [comment]
I have the same problem. If I use fixed values for the center (lat,lng) the map loads. if a pass the values through props, it doesn't load and the map stays grey.

**Comment by DaddyWarbucks** [comment]
You can hard code "&v=3.33" and it works as expected. But you do lose the new Google UI. I am still waiting on a true fix for this.

**Comment by JustFly1984** [comment]
I have gone deep in to the code, and this is what I've dug out:

if you run `npm run build:src`, code generation is broken in `src/tx/ClassDefinition.js` on line 12 there is a `make-fetch-happen` call to "https://developers.google.com/maps/documentation/javascript/3.exp/reference", which actually redirects to `https://developers.google.com/maps/documentation/javascript/reference/`

Fixing it to `https://developers.google.com/maps/documentation/javascript/reference/3.33` does not help, and it returns back something not parsable.

When I run `npm run styleguide`, and navigate to the browser - I see empty map example:

<img width="1826" alt="screenshot 2018-11-24 18 28 54" src="https://user-images.githubusercontent.com/2255993/48973832-d51a0880-f016-11e8-9c12-7d20155859ae.png">

and 2 weird errors:
```
react-dom.development.js:506 Warning: <GoogleMap /> is using incorrect casing. Use PascalCase for React components, or lowercase for HTML elements.
    in GoogleMap (created by Markdown)
    in strong (created by TextRenderer)
    in TextRenderer (created by Styled(Text))
    in Styled(Text) (created by Markdown)
    in p (created by ParaRenderer)
    in ParaRenderer (created by Styled(Para))
    in Styled(Para) (created by Markdown)
    in div (created by Markdown)
    in Markdown (created by Examples)
    in article (created by ExamplesRenderer)
    in ExamplesRenderer (created by Styled(Examples))
    in Styled(Examples) (created by Examples)
    in Examples (created by Section)
    in section (created by SectionRenderer)
    in SectionRenderer (created by Styled(Section))
    in Styled(Section) (created by Section)
    in Section (created by Sections)
    in section (created by SectionsRenderer)
    in SectionsRenderer (created by Styled(Sections))
    in Styled(Sections) (created by Sections)
    in Sections (created by Section)
    in section (created by SectionRenderer)
    in SectionRenderer (created by Styled(Section))
    in Styled(Section) (created by Section)
    in Section (created by Sections)
    in section (created by SectionsRenderer)
    in SectionsRenderer (created by Styled(Sections))
    in Styled(Sections) (created by Sections)
    in Sections (created by StyleGuide)
    in main (created by StyleGuideRenderer)
    in div (created by StyleGuideRenderer)
    in StyleGuideRenderer (created by Styled(StyleGuide))
    in Styled(StyleGuide) (created by StyleGuide)
    in StyleGuide
```

The main reason why I dig in to the project - it imports whole `lodash` library, which is stunning 152k gzip. My whole app is less than `lodash` library, so I wanted to import only really required functions one by one, but this is impossible, due to code generation issues. Please fix code generation, so I could overhaul the codebase.
